# Generated by Django 4.1.2 on 2022-10-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='static',
            field=models.BooleanField(default=False, verbose_name='Фиксация на все разговоры'),
        ),
    ]
