# Generated by Django 4.1.2 on 2022-10-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_dynamicfield_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicfield',
            name='static',
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='changeable',
            field=models.BooleanField(default=True, verbose_name='Разное значение для каждого разговора'),
        ),
    ]
