# Generated by Django 4.1.2 on 2022-10-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_remove_dynamicfield_static_dynamicfield_changeable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='requests_fill',
        ),
    ]
