# Generated by Django 4.1.2 on 2022-11-29 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_remove_phrase_requests_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='timer',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Таймер'),
            preserve_default=False,
        ),
    ]
