# Generated by Django 4.1.2 on 2022-12-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_phrase_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='timer',
            field=models.DurationField(default='00:00:00', verbose_name='Таймер'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='actions',
            field=models.ManyToManyField(through='tree.Reaction', to='tree.phrase', verbose_name='Связанные действия'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='shortcut',
            field=models.BooleanField(default=False, verbose_name='Быстрый доступ'),
        ),
    ]
